name: Lesson 5 SAST

on:
  push:
    branches:
      - lesson-5
jobs:
  security_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
  build_and_test:
    uses: [security_test]
    name: Execute the PyCharm security test
    steps:
      - uses: actions/checkout@v4
      - name: Run PyCharm Security
        uses: tonybaloney/pycharm-security@v1.25.1
  deploy:
    needs: [build_and_test]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: '**PLACEHOLDER** Deploy to Elastic Beanstalk'
        run: echo Placeholder for Deployment
